### ISSUE TITLE
empty string is converted to 0

### ISSUE THREAD

**Issue by sgehrman** [jackypan1989/express-query-parser#17]
you need to add the if (target === '') { to your code.

export const parse = (target: ParsedQuery, options: Options): ParsedQuery => {
  switch (typeof target) {
    case 'string':
      if (target === '') {
        return '';
      } else if (options.parseNull && target === 'null') {
        return null;

**Comment by jackypan1989** [comment]
Yup, thanks!

**Comment by jackypan1989** [comment]
fix by https://github.com/jackypan1989/express-query-parser/releases/tag/v1.3.3

@sgehrman
