### ISSUE TITLE
There are no types for library

### ISSUE THREAD

**Issue by eden-lane** [jackypan1989/express-query-parser#4]
![image](https://user-images.githubusercontent.com/2963477/103854696-29cb5100-50c2-11eb-9d59-c072cc0b9e9a.png)
![image](https://user-images.githubusercontent.com/2963477/103854718-38196d00-50c2-11eb-9782-0aead81dd645.png)

**Comment by moomoolive** [comment]
I ran into the same problem @eden-lane , did you end up fixing it?

**Comment by eden-lane** [comment]
@moomoolive unfortunately I don't remember if I did. In the end I stopped using this library and wrote my own version of it. It's just a few lines of code so it worked for me

**Comment by moomoolive** [comment]
thanks for the update @eden-lane , I honestly ended up uninstalling it as well. I just ended up using the extended express query parser with [this nifty package](https://www.npmjs.com/package/express-query-boolean) parse booleans.

**Comment by jackypan1989** [comment]
@eden-lane @moomoolive 

v1.2.0 add type declare
https://github.com/jackypan1989/express-query-parser/releases/tag/v1.2.0
